spring:
    datasource:
        url: jdbc:postgresql://localhost:5433/library_db
        username: library_user
        password: library_pass
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
        properties:
            hibernate:
                format_sql: true

    flyway:
        enabled: true
        locations:
            - classpath:db/migration

management:
    endpoints:
        web:
            base-path: /actuator
            exposure:
                include:
                    - health
                    - info

app:
    jwt:
        secret: ${JWT_SECRET}
        access-token-expiration: 900000 #15 min
        refresh-token-expiration: 604800000 # 7d
        email-verification-token-expiration: 86400000 #1d

circulation:
    reservation:
        hold-duration: 2d
    fine:
        overdue-amount: 50