server:
    servlet:
        context-path: /api/v1

spring:
    datasource:
        url: jdbc:postgresql://localhost:5433/library_db
        username: library_user
        password: library_pass
        driver-class-name: org.postgresql.Driver
        hikari:
            maximum-pool-size: 10
            minimum-idle: 2
    #            TODO test loads later

    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
        properties:
            hibernate:
                format_sql: false
        open-in-view: false

    flyway:
        enabled: true
        locations: classpath:db/migration

    modulith:
        events:
            jdbc-schema-initialization:
                enabled: false

management:
    endpoints:
        web:
            exposure:
                include: health, info, prometheus, modulith

    endpoint:
        health:
            show-details: always

    metrics:
        tags:
            application: ${spring.application.name}

logging:
    level:
        org.hibernate.SQL: DEBUG
        org.hibernate.orm.jdbc.bind: TRACE

app:
    jwt:
        secret: kjawdxkjabsclxjabdx
        access-token-expiration-ms: 36000000