CREATE TABLE addresses
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    street         VARCHAR(255) NOT NULL,
    city           VARCHAR(100) NOT NULL,
    state_province VARCHAR(100) NOT NULL,
    postal_code    VARCHAR(20)  NOT NULL,
    country        VARCHAR(100) NOT NULL DEFAULT 'India',
    latitude       DECIMAL(9, 6),
    longitude      DECIMAL(9, 6),

    created_at     TIMESTAMPTZ           DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMPTZ           DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_latitude
        CHECK (latitude BETWEEN -90 AND 90),

    CONSTRAINT chk_longitude
        CHECK (longitude BETWEEN -180 AND 180)
);

CREATE INDEX idx_addresses_city_state ON addresses (city, state_province);

CREATE TABLE branches
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(150) NOT NULL,
    address_id    BIGINT       NOT NULL,
    phone         VARCHAR(20),
    email         VARCHAR(100),
    opening_hours VARCHAR(100),
    is_active     BOOLEAN     DEFAULT true,

    created_at    TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (address_id) REFERENCES addresses (id) ON DELETE RESTRICT
);

CREATE INDEX idx_branches_is_active ON branches (is_active);

CREATE TABLE users
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username            VARCHAR(50) UNIQUE  NOT NULL,
    email               VARCHAR(100) UNIQUE NOT NULL,
    password_hash       VARCHAR(255)        NOT NULL,
    email_verified_at   TIMESTAMPTZ,
    first_name          VARCHAR(100),
    last_name           VARCHAR(100),
    phone               VARCHAR(20),
    address_id          BIGINT,
    address_verified_at TIMESTAMPTZ,
    preferred_branch_id BIGINT,
    user_role           VARCHAR(20)         NOT NULL DEFAULT 'MEMBER' CHECK (user_role IN ('MEMBER', 'LIBRARIAN', 'ADMIN')),
    account_status      VARCHAR(20)         NOT NULL DEFAULT 'PENDING_PROFILE' CHECK ( account_status IN
                                                                                       ('PENDING_PROFILE', 'ACTIVE',
                                                                                        'SUSPENDED', 'DEACTIVATED')),
    last_login_at       TIMESTAMPTZ,

    created_at          TIMESTAMPTZ                  DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ                  DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (address_id) REFERENCES addresses (id) ON DELETE SET NULL,
    FOREIGN KEY (preferred_branch_id) REFERENCES branches (id) ON DELETE SET NULL
);

CREATE INDEX idx_users_user_role ON users (user_role);
CREATE INDEX idx_users_account_status ON users (account_status);

CREATE TABLE publishers
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(200) NOT NULL UNIQUE,
    address_id BIGINT,
    phone      VARCHAR(20),
    email      VARCHAR(100),

    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (address_id) REFERENCES addresses (id) ON DELETE SET NULL
);

CREATE INDEX idx_publishers_name ON publishers (name);

CREATE TABLE authors
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(200) NOT NULL,
    biography     TEXT,
    date_of_birth DATE,
    nationality   VARCHAR(100),

    created_at    TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_authors_name ON authors (name);

CREATE TABLE categories
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(500),

    created_at  TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_categories_name ON categories (name);

CREATE TABLE books
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title            VARCHAR(300) NOT NULL,
    isbn             VARCHAR(17) UNIQUE,
    category_id      BIGINT       NOT NULL,
    publisher_id     BIGINT,
    publication_year SMALLINT CHECK (publication_year BETWEEN 600 AND EXTRACT(YEAR FROM CURRENT_DATE) + 1),
    description      TEXT,
    language         VARCHAR(50) DEFAULT 'English',
    pages            INT,
    is_active        BOOLEAN     DEFAULT true,

    created_at       TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE RESTRICT,
    FOREIGN KEY (publisher_id) REFERENCES publishers (id) ON DELETE SET NULL
);

CREATE INDEX idx_books_title ON books (title);
CREATE INDEX idx_books_isbn ON books (isbn);
CREATE INDEX idx_books_category_id ON books (category_id);
CREATE INDEX idx_books_is_active ON books (is_active);

CREATE TABLE book_authors
(
    book_id      BIGINT   NOT NULL,
    author_id    BIGINT   NOT NULL,
    author_order SMALLINT NOT NULL DEFAULT 0,

    PRIMARY KEY (book_id, author_id),
    UNIQUE (book_id, author_order),
    FOREIGN KEY (book_id) REFERENCES books (id) ON DELETE CASCADE,
    FOREIGN KEY (author_id) REFERENCES authors (id) ON DELETE RESTRICT
);

CREATE TABLE book_copies
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id            BIGINT      NOT NULL,
    branch_id          BIGINT      NOT NULL,
    barcode            VARCHAR(50) UNIQUE,
    status             VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE' CHECK (status IN
                                                                       ('AVAILABLE', 'LOANED', 'RESERVED',
                                                                        'UNDER_MAINTENANCE', 'LOST', 'WITHDRAWN')),
    physical_condition VARCHAR(20)          DEFAULT 'GOOD' CHECK (physical_condition IN ('NEW', 'GOOD', 'FAIR', 'POOR')),
    acquisition_date   DATE,

    created_at         TIMESTAMPTZ          DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMPTZ          DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (book_id) REFERENCES books (id) ON DELETE CASCADE,
    FOREIGN KEY (branch_id) REFERENCES branches (id) ON DELETE RESTRICT
);

CREATE INDEX idx_book_copies_branch_id ON book_copies (branch_id);
CREATE INDEX idx_book_copies_book_id ON book_copies (book_id);
CREATE INDEX idx_book_copies_status ON book_copies (status);

CREATE TABLE loans
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_copy_id     BIGINT      NOT NULL,
    user_id          BIGINT      NOT NULL,

    borrow_branch_id BIGINT      NOT NULL,
    return_branch_id BIGINT,

    issued_by        BIGINT      NOT NULL,
    returned_by      BIGINT,

    loan_date        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    due_date         TIMESTAMPTZ NOT NULL,
    return_date      TIMESTAMPTZ,
    status           VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'RETURNED')),

    created_at       TIMESTAMPTZ          DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ          DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (book_copy_id) REFERENCES book_copies (id) ON DELETE RESTRICT,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    FOREIGN KEY (borrow_branch_id) REFERENCES branches (id) ON DELETE RESTRICT,
    FOREIGN KEY (return_branch_id) REFERENCES branches (id) ON DELETE SET NULL,
    FOREIGN KEY (issued_by) REFERENCES users (id) ON DELETE RESTRICT,
    FOREIGN KEY (returned_by) REFERENCES users (id) ON DELETE RESTRICT,
    CHECK (due_date >= loan_date),
    CHECK (return_date IS NULL OR return_date >= loan_date),
    CHECK ( (status = 'RETURNED' AND return_date IS NOT NULL) OR (status = 'ACTIVE' AND return_date IS NULL) )
);

CREATE INDEX idx_loans_user_id ON loans (user_id);
CREATE INDEX idx_loans_status ON loans (status);
CREATE INDEX idx_loans_due_date ON loans (due_date);
CREATE INDEX idx_loans_borrow_branch ON loans (borrow_branch_id);
CREATE INDEX idx_loans_return_branch ON loans (return_branch_id);
CREATE UNIQUE INDEX idx_loans_active_book_copy ON loans (book_copy_id) WHERE status = 'ACTIVE';

CREATE TABLE reservations
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id          BIGINT      NOT NULL,
    user_id          BIGINT      NOT NULL,
    pickup_branch_id BIGINT      NOT NULL,
    reservation_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status           VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'READY', 'FULFILLED', 'CANCELLED')),
    ready_until      TIMESTAMPTZ CHECK ( ready_until IS NULL OR ready_until >= reservation_date ),

    created_at       TIMESTAMPTZ          DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ          DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (book_id) REFERENCES books (id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (pickup_branch_id) REFERENCES branches (id) ON DELETE RESTRICT
);

CREATE INDEX idx_reservations_user_id ON reservations (user_id);
CREATE INDEX idx_reservations_book_id ON reservations (book_id);
CREATE INDEX idx_reservations_status ON reservations (status);
CREATE INDEX idx_reservations_pickup_branch ON reservations (pickup_branch_id);
CREATE INDEX idx_reservations_book_status_date ON reservations (book_id, status, reservation_date);
CREATE UNIQUE INDEX idx_reservations_unique_pending ON reservations (book_id, user_id) WHERE status = 'PENDING';


CREATE TABLE fines
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_id    BIGINT         NOT NULL,
    amount     DECIMAL(10, 2) NOT NULL CHECK (amount >= 0),
    reason     VARCHAR(20)    NOT NULL CHECK (reason IN ('OVERDUE', 'DAMAGE', 'LOSS', 'OTHER')),
    paid_at    TIMESTAMPTZ,

    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (loan_id) REFERENCES loans (id) ON DELETE CASCADE,
    CHECK (paid_at IS NULL OR paid_at >= created_at)
);

CREATE INDEX idx_fines_loan_id ON fines (loan_id);
CREATE INDEX idx_fines_paid_at ON fines (paid_at);